#!/usr/bin/perl
# ... cause I was high when I wrote this...

use strict;
use feature 'say';
use Getopt::Long;

my $DEBUG = 0;

our($opt_r_step, $opt_g_step, $opt_b_step) = (10) x 3;
our $opt_hex = '000000';
our $opt_starting_point = 17;  # Start from 17
our $opt_endpoint       = 231; # End at 231
our $opt_ansi_only      = 0;

GetOptions(
  'hex:s'        => \$opt_hex,
  'red:i'        => \$opt_r_step,
  'g|green:i'    => \$opt_g_step,
  'blue:i'       => \$opt_b_step,
  'start:i'      => \$opt_starting_point,
  'end:i'        => \$opt_endpoint,
  'ansi'         => \$opt_ansi_only,
);

say "R Step: $opt_r_step";
say "G Step: $opt_g_step";
say "B Step: $opt_b_step";
say "ANSI: $opt_starting_point";
say " END: $opt_endpoint";

set_shade(make_shade());


sub set_shade {
  my @colors = @_;

  my $i = $opt_starting_point;

  for my $color(@colors) {
    my ($r, $g, $b) = $color =~ /(..)(..)(..)/;
    printf("\e]4;$i;rgb:$r/$g/$b\e\\");
    $i++;
  }
}

sub make_shade {
  my @tint = ();
  my ($r, $g, $b) = $opt_hex =~ /(..)(..)(..)/; #FIXME

  $opt_starting_point = 0 if($opt_starting_point == 1); # Include ANSI
  $opt_endpoint     = 255 if($opt_endpoint == 1); # Include greyscale

  if($opt_ansi_only) {
    $opt_starting_point = 0;
    $opt_endpoint     = 16;
  }

  for ($opt_starting_point .. $opt_endpoint) {

    $r = (($r + $opt_r_step) < (255 - ($opt_r_step + $r)))
      ? ($r + $opt_r_step)
      : (255 - ($opt_r_step++))
      ;

    $g = (($g + $opt_g_step) < (255 - ($opt_g_step + $g)))
      ? ($g + $opt_g_step)
      : (255 - ($opt_g_step++))
      ;

    $b = (($b + $opt_b_step) < (255 - ($opt_b_step + $b)))
      ? ($b + $opt_b_step)
      : (255 - ($opt_b_step++))
      ;

    my $hex_r = sprintf("%02x", $r);
    my $hex_g = sprintf("%02x", $g);
    my $hex_b = sprintf("%02x", $b);

    do {
      say "\e[1m$hex_r$hex_g$hex_b\e[0m";
      say "\e[38;5;160m0xR\e[0m: $hex_r";
      say "\e[38;5;148m0xG\e[0m: $hex_g";
      say "\e[38;5;033m0xB\e[0m: $hex_b";
    } if($DEBUG);

    push(@tint, $hex_r . $hex_g . $hex_b);

  }
  return(@tint);
}
