#!/bin/bash
# trapd00r's famous ANSI colorscheme
colorcoke --single  0  030303
colorcoke --single  8  1c1c1c
colorcoke --single  1 ff4747
colorcoke --single  9 ff6767
colorcoke --single  2 2b4626
colorcoke --single  10 b03b31
colorcoke --single  3  ff8f00
colorcoke --single  11  df1ed1
colorcoke --single  4  1165e9
colorcoke --single  12  5496ff
colorcoke --single  5  aef7af
colorcoke --single  13  b50077
colorcoke --single  6  cb1c13
colorcoke --single  14  6be603
colorcoke --single  7  ffffff
colorcoke --single  15  dedede
