#!/bin/bash
# trapd00r's famous ANSI colorscheme
colorcoke --single  030303  0
colorcoke --single  1c1c1c  8
colorcoke --single  ff4747  1
colorcoke --single  ff6767  9
colorcoke --single  2b4626  2
colorcoke --single  b03b31  10
colorcoke --single  ff8f00  3
colorcoke --single  bdf1ed  11
colorcoke --single  1165e9  4
colorcoke --single  5496ff  12
colorcoke --single  aef7af  5
colorcoke --single  b50077  13
colorcoke --single  cb1c13  6
colorcoke --single  6be603  14
colorcoke --single  ffffff  7
colorcoke --single  dedede  15
